create entity and setting
f-lab-edu/pay_pay pull request #1
Opened 2024-11-18 12:58 UTC by sue4869

erd : https://www.erdcloud.com/d/Zre9oDeN9hsLf4vkv
관련 정리 : https://summin.notion.site/1412ded991338011a6d8eb7ca321ecbe?pvs=4

2024-12-02 13:52 UTC, f-lab-justin requested changes
@sue4869 
확인 부탁드립니다!!

2024-12-02 13:52 UTC, f-lab-justin commented on build.gradle
>  group = 'sumin.com'
@sue4869 
이 부분은 규칙을 한 번 살펴보시면 좋을 것 같습니다~!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/entity/Account.java
> +
@sue4869 
여기서는 일단 빌더 패턴으로 만들어보셔도 좋을듯합니다. 저는 기본 생성자를 좋아하긴 합니다.

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/entity/Account.java
> +
@sue4869 
kotlin에서 많이 사용하는 방법인데, 자바에서는 직접적으로 필드에 값을 셋팅하는 걸 지양하고 있습니다~! OCP에 따라 함수를 통해서 설정할 수 있도록 해보세요!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/exception/CommonResultCode.java
> +	URI_NOT_FOUND(NOT_FOUND, "url not found");
@sue4869 
NOT_FOUND도 HttpStatus를 일관되게 작성하면 좋을 듯 합니다!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/service/AccountService.java
> +	public AccountCreateResponse create(AccountCreateRequest request) {
@sue4869 
AccountCreateRequest를 서비스로 넘기면 dependency가 어떻게 될까요? 
이번 정도의 클래스 규모로는 단순해서 가능하긴 합니다!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/service/AccountService.java
> +	public AccountCreateResponse create(AccountCreateRequest request) {
@sue4869 
parameter 개수에 따라 굳이 class를 넘기지 않는게 좀 더 명확할 수 있습니다~!

public AccountCreateResponse create(Long userId) {
}

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/service/AccountService.java
> +		do {
@sue4869 
retry 로직에 대해서 살펴보시면 좋을 것 같습니다~! 
while문은 무한루프를 항상 조심해야 하기 때문에 안전한 방법을 고민하는게 좋습니다!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/service/AccountService.java
> +	public void validUser(Long userId) {
@sue4869 
이부분을 테스트할 수 있는 코드를 작성해보세요~!
mockito를 사용해서 테스트해보세요!

2024-12-02 13:52 UTC, f-lab-justin commented on src/main/java/sumin/com/paypay/service/AccountService.java
> +		do {
@sue4869 
accountRepository.existsByAccountNumber에서 값이 있는 상황을 테스트 코드로 어떻게 테스트할 수 있을까요? 
한번 살펴보세요!

2024-12-30 13:53 UTC, f-lab-justin requested changes
@sue4869 
리뷰 살펴봐 주세요!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/controller/AccountApi.java
> +		return accountService.create(request);
@sue4869 
여기서 controller와 service의 결합을 느슨하게 하려면 어떻게 하면 좋을까요?
다음의 코드를 참고하셔요~!

https://github.com/rbailen/Hexagonal-Architecture/blob/main/poc-hexagonal_architecture/src/main/java/es/rbailen/sample/hexagonalarchitecture/infrastructure/adapter/input/rest/ProductRestAdapter.java

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/controller/AccountApi.java
> +		@ModelAttribute AccountDetailRequest request
@sue4869
Get인데 body가 있는 건 표준은 아닙니다. 
보통 권한은 header를 활용하고 있는데요. 
인증 토큰과 관련된 부분에 대한 고민이 필요합니다.

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/controller/TransactionApi.java
> +	public ResponseEntity<String> transfer(@RequestParam Long fromAccountId,
@sue4869 
Post에서는 json body를 사용하는 것이 표준입니다.
queryparam은 잘 사용하지 않아요~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/controller/TransactionApi.java
> +		return ResponseEntity.ok("송금이 완료되었습니다.");
@sue4869 
대다수의 함수는 응답을 주어야 하고, 이 응답을 받아서 처리할 수 있도록 하면 좋습니다.
동일한 input에 동일한 output을 주는 것의 장점에 대해서 한번 살펴보시면 좋습니다~!(참조 투명성. Referential Transparency)

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/entity/Account.java
> +		this.balance = balance;
@sue4869 
다음과 같이 처리하면 명확합니다~!

```java
public Account changeBalance(BigDecimal balance) {
   this.balance = balance;
   return this;
} 
```

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/exception/ErrorResponse.java
> +	private final String message;
@sue4869 
code도 보통 추가합니다! 참고 부탁드려요~!

https://developers.facebook.com/docs/graph-api/guides/error-handling/
https://cloud.google.com/apis/design/errors?hl=ko

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/model/dto/AccountDto.java
> +	private Instant transactionAt;
@sue4869 
LocalDateTime, ZonedDateTime, Instant 등 시간관련해서 한번 정리를 해보시면 도움이 됩니다~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/model/request/AccountDeleteRequest.java
> +	}
@sue4869 
이건 버그인 것 같습니다~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/model/request/AccountDetailRequest.java
> +	}
@sue4869 
요것도 위와 동일합니다~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		validUser(request.getUserId());
@sue4869 
validation도 validation의 결과 혹은 진행하면서 가져온 값들을 같이 리턴해주는 방식을 사용해보면 좋습니다.

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		return dtos.stream().map(AccountGetResponse::to).toList();
@sue4869 
여기는 좀 더 간결하게 할 수 있을 듯 합니다~! 
위의 코드에 map(AccountGetResponse::to)를 추가해주면 one line으로 끝날 것 같아요~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		} while (accountRepository.existsByAccountNumber(accountNumber));
@sue4869 
여기는 수정이 필요할 것 같습니다~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		} while (accountRepository.existsByAccountNumber(accountNumber));
@sue4869 
id 생성 로직은 다양한 개념들이 있는데 "가상 면접 사례로 배우는 대규모 시스템 설계 기초"에 있는 "7장 분산 시스템을 위한 유일 ID 생성기 설계" 여기 한번 살펴보시고 알아보기 시작하면 도움이 됩니다~!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		return AccountMapper.INSTANCE.toAccountDto(accountOptional.get());
@sue4869 
좀 더 간결하게 한줄로 코드를 작성할 수 있습니다~!
이런 거 줄이면 뿌듯한데 한번 살펴보세요!

2024-12-30 13:53 UTC, f-lab-justin commented on src/main/java/com/sumin/paypay/service/AccountService.java
> +		Optional<Account> optionalAccount = accountRepository.findByIdAndUserId(accountId, userId);
@sue4869 
좀 더 간결하게 한줄로 코드를 작성할 수 있습니다~!
이런 거 줄이면 뿌듯한데 한번 살펴보세요!

2025-01-02 12:52 UTC, sue4869 commented
넵 해당 내용 반영해서 다음 pr에 올리도록 하겠습니당~!

2025-01-02 12:52 UTC, merged